### ISSUE TITLE
Use Cesium sun as lightsource for material

### ISSUE THREAD

**Issue by laurensdijkstra** [AnalyticalGraphicsInc/collada2gltf-web-service#2]
When converting Collada models to glTF via the web service you provide and then displaying the model in Cesium makes the model unaffected by the lighting direction of the sun. I saw that the obj2gltf library added a --cesium flag to address this issue. Would it be possible for the web service to provide a similar feature? 

As a side note, it is not possible for us to use obj2gltf because of limitations in storing model hierarchies in the obj format, which are needed for rotating parts of the models we use.

**Comment by pjcozzi** [comment]
@laurensdijkstra I moved this to https://github.com/AnalyticalGraphicsInc/cesium/issues/4207 since this repo is just example code, not the actual model converter used on cesiumjs.org.

**Comment by laurensdijkstra** [comment]
Thanks! I was already wondering if this was the right repo because I didn't see any updates since a long time yet online al kinds of new features were added.
